package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArticulosXPuntoVentaId generated by hbm2java
 */
@Embeddable
public class AsistenciaXSalaId implements java.io.Serializable {

	private int idAsientosXSala;
	private int idProgramacion;
	private Date fechaExhibicion;

	public AsistenciaXSalaId() {
	}
	
	public AsistenciaXSalaId(int idAsientosXSala, int idProgramacion, Date fechaExhibicion) {
		this.idAsientosXSala = idAsientosXSala;
		this.idProgramacion = idProgramacion;
		this.fechaExhibicion = fechaExhibicion;
	}
	

	@Column(name = "id_asientos_x_sala", nullable = false)
	public int getIdAsientosXSala() {
		return this.idAsientosXSala;
	}

	public void setIdAsientosXSala(int idAsientosXSala) {
		this.idAsientosXSala = idAsientosXSala;
	}

	@Column(name = "id_programacion", nullable = false)
	public int getIdProgramacion() {
		return this.idProgramacion;
	}

	public void setIdProgramacion(int idProgramacion) {
		this.idProgramacion = idProgramacion;
	}
	
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_exhibicion", nullable = false, length = 10)
	public Date getFechaExhibicion() {
		return this.fechaExhibicion;
	}

	public void setFechaExhibicion(Date fechaExhibicion) {
		this.fechaExhibicion = fechaExhibicion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AsistenciaXSalaId))
			return false;
		AsistenciaXSalaId castOther = (AsistenciaXSalaId) other;

		return (this.getIdAsientosXSala() == castOther.getIdAsientosXSala())
				&& (this.getIdProgramacion() == castOther.getIdProgramacion())
				&& (this.getFechaExhibicion() == castOther.getFechaExhibicion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAsientosXSala();
		result = 37 * result + this.getIdProgramacion();
		result = 37 * result + this.getFechaExhibicion().hashCode();
		return result;
	}

}
