package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 28-may-2017 1:39:12 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AutorizacionMovimiento generated by hbm2java
 */
@Entity
@Table(name = "autorizacion_movimiento", catalog = "posaztlanbd")
public class AutorizacionMovimiento implements java.io.Serializable {

	private AutorizacionMovimientoId id;
	private Autorizacion autorizacion;
	private MovimientoInventario movimientoInventario;

	public AutorizacionMovimiento() {
	}

	public AutorizacionMovimiento(AutorizacionMovimientoId id, Autorizacion autorizacion,
			MovimientoInventario movimientoInventario) {
		this.id = id;
		this.autorizacion = autorizacion;
		this.movimientoInventario = movimientoInventario;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idAutorizacion", column = @Column(name = "id_autorizacion", nullable = false)),
			@AttributeOverride(name = "idMovimientoInventario", column = @Column(name = "id_movimiento_inventario", nullable = false)) })
	public AutorizacionMovimientoId getId() {
		return this.id;
	}

	public void setId(AutorizacionMovimientoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_autorizacion", nullable = false, insertable = false, updatable = false)
	public Autorizacion getAutorizacion() {
		return this.autorizacion;
	}

	public void setAutorizacion(Autorizacion autorizacion) {
		this.autorizacion = autorizacion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_movimiento_inventario", nullable = false, insertable = false, updatable = false)
	public MovimientoInventario getMovimientoInventario() {
		return this.movimientoInventario;
	}

	public void setMovimientoInventario(MovimientoInventario movimientoInventario) {
		this.movimientoInventario = movimientoInventario;
	}

}
