package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 28-may-2017 1:39:12 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AutorizacionMovimientoId generated by hbm2java
 */
@Embeddable
public class AutorizacionMovimientoId implements java.io.Serializable {

	private int idAutorizacion;
	private int idMovimientoInventario;

	public AutorizacionMovimientoId() {
	}

	public AutorizacionMovimientoId(int idAutorizacion, int idMovimientoInventario) {
		this.idAutorizacion = idAutorizacion;
		this.idMovimientoInventario = idMovimientoInventario;
	}

	@Column(name = "id_autorizacion", nullable = false)
	public int getIdAutorizacion() {
		return this.idAutorizacion;
	}

	public void setIdAutorizacion(int idAutorizacion) {
		this.idAutorizacion = idAutorizacion;
	}

	@Column(name = "id_movimiento_inventario", nullable = false)
	public int getIdMovimientoInventario() {
		return this.idMovimientoInventario;
	}

	public void setIdMovimientoInventario(int idMovimientoInventario) {
		this.idMovimientoInventario = idMovimientoInventario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AutorizacionMovimientoId))
			return false;
		AutorizacionMovimientoId castOther = (AutorizacionMovimientoId) other;

		return (this.getIdAutorizacion() == castOther.getIdAutorizacion())
				&& (this.getIdMovimientoInventario() == castOther.getIdMovimientoInventario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAutorizacion();
		result = 37 * result + this.getIdMovimientoInventario();
		return result;
	}

}
