package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PuntoVenta generated by hbm2java
 */
@Entity
@Table(name = "caja", catalog = "posaztlanbd")
public class Caja implements java.io.Serializable {

	private Integer idCaja;
	private PuntoVenta puntoVenta;
	private String nombre;
	private boolean activo;
	private Set<TicketVenta> ticketVentas = new HashSet<TicketVenta>(0);
	private Set<CorteCaja> corteCajas = new HashSet<CorteCaja>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Caja() {
	}
	
	public Caja(Integer idCaja) {
		this.idCaja = idCaja;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_caja", unique = true, nullable = false)
	public Integer getIdCaja() {
		return this.idCaja;
	}

	public void setIdCaja(Integer idCaja) {
		this.idCaja = idCaja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_punto_venta", nullable = false)
	public PuntoVenta getPuntoVenta() {
		return this.puntoVenta;
	}

	public void setPuntoVenta(PuntoVenta puntoVenta) {
		this.puntoVenta = puntoVenta;
	}
	
	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caja")
	public Set<TicketVenta> getTicketVentas() {
		return this.ticketVentas;
	}

	public void setTicketVentas(Set<TicketVenta> ticketVentas) {
		this.ticketVentas = ticketVentas;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caja")
	public Set<CorteCaja> getCorteCajas() {
		return this.corteCajas;
	}

	public void setCorteCajas(Set<CorteCaja> corteCajas) {
		this.corteCajas = corteCajas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caja")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
