package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 09-jul-2017 19:14:48 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Devolucion generated by hbm2java
 */
@Entity
@Table(name = "devolucion", catalog = "posaztlanbd")
public class Devolucion implements java.io.Serializable {

	private Integer idDevolucion;
	private Autorizacion autorizacion;
	private MotivoDevolucion motivoDevolucion;
	private TicketVenta ticketVenta;
	private TipoDevolucion tipoDevolucion;
	private Usuario usuario;
	private Date fechaHora;
	private Integer folio;
	private String comentarios;
	private Set<DevolucionXProducto> devolucionXProductos = new HashSet<DevolucionXProducto>(0);

	public Devolucion() {
	}

	public Devolucion(Autorizacion autorizacion, MotivoDevolucion motivoDevolucion, TicketVenta ticketVenta,
			TipoDevolucion tipoDevolucion, Usuario usuario, Date fechaHora) {
		this.autorizacion = autorizacion;
		this.motivoDevolucion = motivoDevolucion;
		this.ticketVenta = ticketVenta;
		this.tipoDevolucion = tipoDevolucion;
		this.usuario = usuario;
		this.fechaHora = fechaHora;
	}

	public Devolucion(Autorizacion autorizacion, MotivoDevolucion motivoDevolucion, TicketVenta ticketVenta,
			TipoDevolucion tipoDevolucion, Usuario usuario, Date fechaHora, Integer folio, String comentarios,
			Set<DevolucionXProducto> devolucionXProductos) {
		this.autorizacion = autorizacion;
		this.motivoDevolucion = motivoDevolucion;
		this.ticketVenta = ticketVenta;
		this.tipoDevolucion = tipoDevolucion;
		this.usuario = usuario;
		this.fechaHora = fechaHora;
		this.folio = folio;
		this.comentarios = comentarios;
		this.devolucionXProductos = devolucionXProductos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_devolucion", unique = true, nullable = false)
	public Integer getIdDevolucion() {
		return this.idDevolucion;
	}

	public void setIdDevolucion(Integer idDevolucion) {
		this.idDevolucion = idDevolucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_autorizacion", nullable = false)
	public Autorizacion getAutorizacion() {
		return this.autorizacion;
	}

	public void setAutorizacion(Autorizacion autorizacion) {
		this.autorizacion = autorizacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_motivo_devolucion", nullable = false)
	public MotivoDevolucion getMotivoDevolucion() {
		return this.motivoDevolucion;
	}

	public void setMotivoDevolucion(MotivoDevolucion motivoDevolucion) {
		this.motivoDevolucion = motivoDevolucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ticket_venta", nullable = false)
	public TicketVenta getTicketVenta() {
		return this.ticketVenta;
	}

	public void setTicketVenta(TicketVenta ticketVenta) {
		this.ticketVenta = ticketVenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_devolucion", nullable = false)
	public TipoDevolucion getTipoDevolucion() {
		return this.tipoDevolucion;
	}

	public void setTipoDevolucion(TipoDevolucion tipoDevolucion) {
		this.tipoDevolucion = tipoDevolucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_hora", nullable = false, length = 19)
	public Date getFechaHora() {
		return this.fechaHora;
	}

	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}

	@Column(name = "folio")
	public Integer getFolio() {
		return this.folio;
	}

	public void setFolio(Integer folio) {
		this.folio = folio;
	}

	@Column(name = "comentarios", length = 250)
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "devolucion")
	public Set<DevolucionXProducto> getDevolucionXProductos() {
		return this.devolucionXProductos;
	}

	public void setDevolucionXProductos(Set<DevolucionXProducto> devolucionXProductos) {
		this.devolucionXProductos = devolucionXProductos;
	}

}
