package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 09-jul-2017 19:14:48 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DevolucionXProducto generated by hbm2java
 */
@Entity
@Table(name = "devolucion_x_producto", catalog = "posaztlanbd")
public class DevolucionXProducto implements java.io.Serializable {

	private Integer idDevolucionXProducto;
	private Devolucion devolucion;
	private EstadoProducto estadoProducto;
	private Producto producto;
	private TicketVenta ticketVenta;
	private String clave;

	public DevolucionXProducto() {
	}

	public DevolucionXProducto(Devolucion devolucion, EstadoProducto estadoProducto, Producto producto,
			TicketVenta ticketVenta, String clave) {
		this.devolucion = devolucion;
		this.estadoProducto = estadoProducto;
		this.producto = producto;
		this.ticketVenta = ticketVenta;
		this.clave = clave;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_devolucion_x_producto", unique = true, nullable = false)
	public Integer getIdDevolucionXProducto() {
		return this.idDevolucionXProducto;
	}

	public void setIdDevolucionXProducto(Integer idDevolucionXProducto) {
		this.idDevolucionXProducto = idDevolucionXProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_devolucion", nullable = false)
	public Devolucion getDevolucion() {
		return this.devolucion;
	}

	public void setDevolucion(Devolucion devolucion) {
		this.devolucion = devolucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_producto", nullable = false)
	public EstadoProducto getEstadoProducto() {
		return this.estadoProducto;
	}

	public void setEstadoProducto(EstadoProducto estadoProducto) {
		this.estadoProducto = estadoProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_producto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ticket", nullable = false)
	public TicketVenta getTicketVenta() {
		return this.ticketVenta;
	}

	public void setTicketVenta(TicketVenta ticketVenta) {
		this.ticketVenta = ticketVenta;
	}

	@Column(name = "clave", nullable = false, length = 50)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

}
