package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 29-may-2017 22:51:46 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa", catalog = "posaztlanbd")
public class Empresa implements java.io.Serializable {

	private Integer idEmpresa;
	private Contacto contacto;
	private EstatusEmpresa estatusEmpresa;
	private String nombre;
	private String rfc;
	private String slogan;
	private byte[] icono;
	private Set<Cine> cines = new HashSet<Cine>(0);

	public Empresa() {
	}

	public Empresa(Contacto contacto, EstatusEmpresa estatusEmpresa, String nombre, String rfc, String slogan,
			byte[] icono) {
		this.contacto = contacto;
		this.estatusEmpresa = estatusEmpresa;
		this.nombre = nombre;
		this.rfc = rfc;
		this.slogan = slogan;
		this.icono = icono;
	}

	public Empresa(Contacto contacto, EstatusEmpresa estatusEmpresa, String nombre, String rfc, String slogan,
			byte[] icono, Set<Cine> cines) {
		this.contacto = contacto;
		this.estatusEmpresa = estatusEmpresa;
		this.nombre = nombre;
		this.rfc = rfc;
		this.slogan = slogan;
		this.icono = icono;
		this.cines = cines;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_empresa", unique = true, nullable = false)
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_contacto", nullable = false)
	public Contacto getContacto() {
		return this.contacto;
	}

	public void setContacto(Contacto contacto) {
		this.contacto = contacto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estatus_empresa", nullable = false)
	public EstatusEmpresa getEstatusEmpresa() {
		return this.estatusEmpresa;
	}

	public void setEstatusEmpresa(EstatusEmpresa estatusEmpresa) {
		this.estatusEmpresa = estatusEmpresa;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "rfc", nullable = false, length = 13)
	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	@Column(name = "slogan", nullable = false, length = 100)
	public String getSlogan() {
		return this.slogan;
	}

	public void setSlogan(String slogan) {
		this.slogan = slogan;
	}

	@Column(name = "icono", nullable = false)
	public byte[] getIcono() {
		return this.icono;
	}

	public void setIcono(byte[] icono) {
		this.icono = icono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
	public Set<Cine> getCines() {
		return this.cines;
	}

	public void setCines(Set<Cine> cines) {
		this.cines = cines;
	}

}
