package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstatusOrdenCompra generated by hbm2java
 */
@Entity
@Table(name = "estatus_conteo", catalog = "posAztlanbd")
public class EstatusConteo implements java.io.Serializable {

	private Integer idEstatusConteo;
	private String nombre;
	private Set<InventarioConteo> conteos = new HashSet<InventarioConteo>(0);
	
	public EstatusConteo() {
	}


	public EstatusConteo(Integer idEstatusConteo) {
		this.idEstatusConteo = idEstatusConteo;
	}

	public EstatusConteo(String nombre) {
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_estatus_conteo", unique = true, nullable = false)
	public Integer getIdEstatusConteo() {
		return this.idEstatusConteo;
	}

	public void setIdEstatusConteo(Integer idEstatusConteo) {
		this.idEstatusConteo = idEstatusConteo;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusConteo")
	public Set<InventarioConteo> getConteos() {
		return this.conteos;
	}

	public void setConteos(Set<InventarioConteo> conteos) {
		this.conteos = conteos;
	}


}
