package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstatusOrdenCompra generated by hbm2java
 */
@Entity
@Table(name = "estatus_orden_compra", catalog = "posAztlanbd")
public class EstatusOrdenCompra implements java.io.Serializable {

	private Integer idEstatusOrdenCompra;
	private String nombre;
	private Set<OrdenCompra> ordenesCompra = new HashSet<OrdenCompra>(0);
	
	public EstatusOrdenCompra() {
	}


	public EstatusOrdenCompra(Integer idEstatusOrdenCompra) {
		this.idEstatusOrdenCompra = idEstatusOrdenCompra;
	}

	public EstatusOrdenCompra(String nombre) {
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_estatus_orden_compra", unique = true, nullable = false)
	public Integer getIdEstatusOrdenCompra() {
		return this.idEstatusOrdenCompra;
	}

	public void setIdEstatusOrdenCompra(Integer idEstatusOrdenCompra) {
		this.idEstatusOrdenCompra = idEstatusOrdenCompra;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusOrdenCompra")
	public Set<OrdenCompra> getOrdenesCompra() {
		return this.ordenesCompra;
	}

	public void setOrdenesCompra(Set<OrdenCompra> ordenesCompra) {
		this.ordenesCompra = ordenesCompra;
	}


}
