package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 05-jun-2017 0:25:12 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FolioBoleto generated by hbm2java
 */
@Entity
@Table(name = "folio_boleto", catalog = "posaztlanbd")
public class FolioBoleto implements java.io.Serializable {

	private FolioBoletoId id;
	private TicketVenta ticketVenta;
	private TipoCliente tipoCliente;
	private Cine cine;
	private int folio;

	public FolioBoleto() {
	}
	
	public FolioBoleto(FolioBoletoId id, TipoCliente tipoCliente, TicketVenta ticketVenta, int folio, Cine cine) {
		this.id= id;
		this.tipoCliente= tipoCliente;
		this.ticketVenta=ticketVenta;
		this.folio = folio;
		this.cine = cine;
	}

	
	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "folio", column = @Column(name = "folio", nullable = false)),
			@AttributeOverride(name = "idCine", column = @Column(name = "id_cine", nullable = false)) })
	public FolioBoletoId getId() {
		return this.id;
	}

	public void setId(FolioBoletoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cine", nullable = false, insertable = false, updatable = false)
	public Cine getCine() {
		return this.cine;
	}

	public void setCine(Cine cine) {
		this.cine = cine;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ticket", nullable = false)
	public TicketVenta getTicketVenta() {
		return this.ticketVenta;
	}

	public void setTicketVenta(TicketVenta ticketVenta) {
		this.ticketVenta = ticketVenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_cliente", nullable = false)
	public TipoCliente getTipoCliente() {
		return this.tipoCliente;
	}

	public void setTipoCliente(TipoCliente tipoCliente) {
		this.tipoCliente = tipoCliente;
	}

	@Column(name = "folio", nullable = false, insertable = false, updatable = false)
	public int getFolio() {
		return this.folio;
	}

	public void setFolio(int folio) {
		this.folio = folio;
	}
	
}
