package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Articulo generated by hbm2java
 */
@Entity
@Table(name = "folio_secuencia", catalog = "posaztlanbd")
public class FolioSecuencia implements java.io.Serializable {

	private Integer idEmpresa;
	private Integer ultimoFolioOc;

	public FolioSecuencia() {
	}
	
	public FolioSecuencia(Integer idEmpresa, Integer ultimoFolioOc) {
		this.idEmpresa = idEmpresa;
		this.ultimoFolioOc = ultimoFolioOc;
	}
	

	@Id
	@Column(name = "id_empresa", unique = true, nullable = false)
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "ultimo_folio_oc", nullable = false)
	public Integer getUltimoFolioOc() {
		return this.ultimoFolioOc;
	}

	public void setUltimoFolioOc(Integer ultimoFolioOc) {
		this.ultimoFolioOc = ultimoFolioOc;
	}

}
