package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 05-jun-2017 0:25:12 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FormaPago generated by hbm2java
 */
@Entity
@Table(name = "forma_pago", catalog = "posaztlanbd")
public class FormaPago implements java.io.Serializable {

	private Integer idFormaPago;
	private String nombre;
	private boolean requiereNumCuenta;
	private boolean activo;
	private String clave;
	private Set<Pago> pagos = new HashSet<Pago>(0);

	public FormaPago() {
	}

	public FormaPago(String nombre, boolean requiereNumCuenta, boolean activo, String clave) {
		this.nombre = nombre;
		this.requiereNumCuenta = requiereNumCuenta;
		this.activo = activo;
		this.clave = clave;
	}

	public FormaPago(String nombre, boolean requiereNumCuenta, boolean activo, String clave, Set<Pago> pagos) {
		this.nombre = nombre;
		this.requiereNumCuenta = requiereNumCuenta;
		this.activo = activo;
		this.clave = clave;
		this.pagos = pagos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_forma_pago", unique = true, nullable = false)
	public Integer getIdFormaPago() {
		return this.idFormaPago;
	}

	public void setIdFormaPago(Integer idFormaPago) {
		this.idFormaPago = idFormaPago;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "requiere_num_cuenta", nullable = false)
	public boolean isRequiereNumCuenta() {
		return this.requiereNumCuenta;
	}

	public void setRequiereNumCuenta(boolean requiereNumCuenta) {
		this.requiereNumCuenta = requiereNumCuenta;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "clave", nullable = false, length = 25)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formaPago")
	public Set<Pago> getPagos() {
		return this.pagos;
	}

	public void setPagos(Set<Pago> pagos) {
		this.pagos = pagos;
	}

}
