package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 09-jul-2017 19:14:48 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdenCompraDetalleId generated by hbm2java
 */
@Embeddable
public class InventarioConteoDetalleId implements java.io.Serializable {

	private int idConteo;
	private int idProducto;
	private int idAlmacen;

	public InventarioConteoDetalleId() {
	}

	public InventarioConteoDetalleId(int idConteo, int idProducto, int idAlmacen) {
		this.idConteo = idConteo;
		this.idProducto = idProducto;
		this.idAlmacen = idAlmacen;
	}

	@Column(name = "id_conteo", nullable = false)
	public int getIdConteo() {
		return this.idConteo;
	}

	public void setIdConteo(int idConteo) {
		this.idConteo = idConteo;
	}

	@Column(name = "id_producto", nullable = false)
	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdAlmacen(int idAlmacen) {
		this.idAlmacen = idAlmacen;
	}

	@Column(name = "id_almacen", nullable = false)
	public int getIdAlmacen() {
		return this.idAlmacen;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InventarioConteoDetalleId))
			return false;
		InventarioConteoDetalleId castOther = (InventarioConteoDetalleId) other;

		return (this.getIdConteo() == castOther.getIdConteo())
				&& (this.getIdProducto() == castOther.getIdProducto())
					&& (this.getIdAlmacen() == castOther.getIdAlmacen());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdConteo();
		result = 37 * result + this.getIdProducto();
		result = 37 * result + this.getIdAlmacen();
		return result;
	}

}
