package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 09-jul-2017 19:14:48 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrdenCompraDetalle generated by hbm2java
 */
@Entity
@Table(name = "inventario_conteo_detalle", catalog = "posAztlanbd")
public class InventarioConteoDetalle implements java.io.Serializable {

	private InventarioConteoDetalleId id;
	private Producto producto;
	private Integer existenciaSistema;	
	private Integer existenciaFisica;
	
	public InventarioConteoDetalle() {
	}

	public InventarioConteoDetalle(InventarioConteoDetalleId id) {
		this.id = id;
	}
	
	public InventarioConteoDetalle(Producto producto, Integer existenciaSistema, Integer existenciaFisica) {
		this.producto = producto;
		this.existenciaSistema = existenciaSistema;
		this.existenciaFisica = existenciaFisica;
		
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idConteo", column = @Column(name = "id_conteo", nullable = false)),
			@AttributeOverride(name = "idProducto", column = @Column(name = "id_producto", nullable = false)) })
	public InventarioConteoDetalleId getId() {
		return this.id;
	}

	public void setId(InventarioConteoDetalleId id) {
		this.id = id;
	}

	@Column(name = "existencia_sistema", nullable = false)
	public Integer getExistenciaSistema() {
		return this.existenciaSistema;
	}

	public void setExistenciaSistema(Integer existenciaSistema) {
		this.existenciaSistema = existenciaSistema;
	}

	@Column(name = "existencia_fisica", nullable = true)
	public Integer getExistenciaFisica() {
		return this.existenciaFisica;
	}

	public void setExistenciaFisica(Integer existenciaFisica) {
		this.existenciaFisica = existenciaFisica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_producto", nullable = false, insertable = false, updatable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}
}
