package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 09-jul-2017 19:14:48 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrdenCompra generated by hbm2java
 */
@Entity
@Table(name = "inventario_conteo", catalog = "posAztlanbd")
public class InventarioConteo implements java.io.Serializable {

	private Integer idConteo;
	private Almacen almacen;
	private int folio;
	private EstatusConteo estatusConteo;
	private Canal canal;
	private Date fechaHora;
	private Usuario usuarioCreador;
	private Usuario usuarioAutorizador;
	
	public InventarioConteo() {
	}

	public InventarioConteo(Integer idConteo) {
		this.idConteo = idConteo;
	}
	
	public InventarioConteo(Almacen almacen, int folio, EstatusConteo estatusConteo, Canal canal) {
		this.almacen = almacen;
		this.folio = folio;
		this.estatusConteo = estatusConteo;
		this.canal = canal;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_conteo", unique = true, nullable = false)
	public Integer getIdConteo() {
		return this.idConteo;
	}

	public void setIdConteo(Integer idConteo) {
		this.idConteo = idConteo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_almacen", nullable = true)
	public Almacen getAlmacen() {
		return this.almacen;
	}

	public void setAlmacen(Almacen almacen) {
		this.almacen = almacen;
	}

	@Column(name = "folio", nullable = false)
	public int getFolio() {
		return this.folio;
	}

	public void setFolio(int folio) {
		this.folio = folio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estatus_conteo", nullable = false)
	public EstatusConteo getEstatusConteo() {
		return this.estatusConteo;
	}

	public void setEstatusConteo(EstatusConteo estatusConteo) {
		this.estatusConteo = estatusConteo;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_canal", nullable = false)
	public Canal getCanal() {
		return this.canal;
	}

	public void setCanal(Canal canal) {
		this.canal = canal;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario_creador", nullable = false)
	public Usuario getUsuarioCreador() {
		return this.usuarioCreador;
	}

	public void setUsuarioCreador(Usuario usuarioCreador) {
		this.usuarioCreador = usuarioCreador;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario_autorizador", nullable = true)
	public Usuario getUsuarioAutorizador() {
		return this.usuarioAutorizador;
	}

	public void setUsuarioAutorizador(Usuario usuarioAutorizador) {
		this.usuarioAutorizador = usuarioAutorizador;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_hora", nullable = false, length = 19)
	public Date getFechaHora() {
		return fechaHora;
	}

	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}
	
}
