package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 16-jul-2017 15:25:04 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MotivoDevolucion generated by hbm2java
 */
@Entity
@Table(name = "motivo_devolucion", catalog = "posaztlanbd")
public class MotivoDevolucion implements java.io.Serializable {

	private Integer idMotivoDevolucion;
	private TipoPuntoVenta tipoPuntoVenta;
	private String nombre;
	private boolean activo;
	private Set<Devolucion> devolucions = new HashSet<Devolucion>(0);

	public MotivoDevolucion() {
	}

	public MotivoDevolucion(TipoPuntoVenta tipoPuntoVenta, String nombre, boolean activo) {
		this.tipoPuntoVenta = tipoPuntoVenta;
		this.nombre = nombre;
		this.activo = activo;
	}

	public MotivoDevolucion(TipoPuntoVenta tipoPuntoVenta, String nombre, boolean activo, Set<Devolucion> devolucions) {
		this.tipoPuntoVenta = tipoPuntoVenta;
		this.nombre = nombre;
		this.activo = activo;
		this.devolucions = devolucions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_motivo_devolucion", unique = true, nullable = false)
	public Integer getIdMotivoDevolucion() {
		return this.idMotivoDevolucion;
	}

	public void setIdMotivoDevolucion(Integer idMotivoDevolucion) {
		this.idMotivoDevolucion = idMotivoDevolucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_punto_venta", nullable = false)
	public TipoPuntoVenta getTipoPuntoVenta() {
		return this.tipoPuntoVenta;
	}

	public void setTipoPuntoVenta(TipoPuntoVenta tipoPuntoVenta) {
		this.tipoPuntoVenta = tipoPuntoVenta;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motivoDevolucion")
	public Set<Devolucion> getDevolucions() {
		return this.devolucions;
	}

	public void setDevolucions(Set<Devolucion> devolucions) {
		this.devolucions = devolucions;
	}

}
