package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovimientoInventario generated by hbm2java
 */
@Entity
@Table(name = "movimiento_inventario", catalog = "posaztlanbd")
public class MovimientoInventario implements java.io.Serializable {

	private Integer idMovimiento;
	private Producto producto;
	private Proveedor proveedor;
	private TipoMovimientoInv tipoMovimientoInv;
	private Usuario usuario;
	private long cantidad;
	private Date fecha;
	private BigDecimal importe;
	private String documentoRespaldo;
	private long existenciaActual;
	private Set<AutorizacionMovimiento> autorizacionMovimientos = new HashSet<AutorizacionMovimiento>(0);
	private Almacen almacen;
	private Almacen almacenConsigna;
    private Inventario inventario;
	
	public MovimientoInventario() {
	}

	public MovimientoInventario (Integer idMovimiento) {
		this.idMovimiento = idMovimiento;
	}
	
	public MovimientoInventario(Producto producto, TipoMovimientoInv tipoMovimientoInv, Usuario usuario, long cantidad,
			Date fecha, BigDecimal importe, long existenciaActual) {
		this.producto = producto;
		this.tipoMovimientoInv = tipoMovimientoInv;
		this.usuario = usuario;
		this.cantidad = cantidad;
		this.fecha = fecha;
		this.importe = importe;
		this.existenciaActual = existenciaActual;
	}

	public MovimientoInventario(Producto producto, Proveedor proveedor, TipoMovimientoInv tipoMovimientoInv,
			Usuario usuario, long cantidad, Date fecha, BigDecimal importe, String documentoRespaldo,
			long existenciaActual, Set<AutorizacionMovimiento> autorizacionMovimientos) {
		this.producto = producto;
		this.proveedor = proveedor;
		this.tipoMovimientoInv = tipoMovimientoInv;
		this.usuario = usuario;
		this.cantidad = cantidad;
		this.fecha = fecha;
		this.importe = importe;
		this.documentoRespaldo = documentoRespaldo;
		this.existenciaActual = existenciaActual;
		this.autorizacionMovimientos = autorizacionMovimientos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_movimiento", unique = true, nullable = false)
	public Integer getIdMovimiento() {
		return this.idMovimiento;
	}

	public void setIdMovimiento(Integer idMovimiento) {
		this.idMovimiento = idMovimiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_producto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proveedor")
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_movimiento", nullable = false)
	public TipoMovimientoInv getTipoMovimientoInv() {
		return this.tipoMovimientoInv;
	}

	public void setTipoMovimientoInv(TipoMovimientoInv tipoMovimientoInv) {
		this.tipoMovimientoInv = tipoMovimientoInv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "cantidad", nullable = false)
	public long getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(long cantidad) {
		this.cantidad = cantidad;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "importe", nullable = false, precision = 15)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Column(name = "documento_respaldo", length = 20)
	public String getDocumentoRespaldo() {
		return this.documentoRespaldo;
	}

	public void setDocumentoRespaldo(String documentoRespaldo) {
		this.documentoRespaldo = documentoRespaldo;
	}

	@Column(name = "existencia_actual", nullable = false)
	public long getExistenciaActual() {
		return this.existenciaActual;
	}

	public void setExistenciaActual(long existenciaActual) {
		this.existenciaActual = existenciaActual;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movimientoInventario")
	public Set<AutorizacionMovimiento> getAutorizacionMovimientos() {
		return this.autorizacionMovimientos;
	}

	public void setAutorizacionMovimientos(Set<AutorizacionMovimiento> autorizacionMovimientos) {
		this.autorizacionMovimientos = autorizacionMovimientos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_almacen", nullable = false)
	public Almacen getAlmacen() {
		return almacen;
	}

	public void setAlmacen(Almacen almacen) {
		this.almacen = almacen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_almacen_consigna", nullable = true)
	public Almacen getAlmacenConsigna() {
		return almacenConsigna;
	}

	public void setAlmacenConsigna(Almacen almacenConsigna) {
		this.almacenConsigna = almacenConsigna;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_inventario", nullable = true)
	public Inventario getInventario() {
		return inventario;
	}

	public void setInventario(Inventario inventario) {
		this.inventario = inventario;
	}	
	

}
