package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 09-jul-2017 19:14:48 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrdenCompraDetalle generated by hbm2java
 */
@Entity
@Table(name = "orden_compra_detalle", catalog = "posAztlanbd")
public class OrdenCompraDetalle implements java.io.Serializable {

	private OrdenCompraDetalleId id;
	private BigDecimal precioUnitario;
	private BigDecimal precioUnitarioFinal;
	private int cantidad;
	//private int cantidadFinal;
	private Producto producto;

	public OrdenCompraDetalle() {
	}

	public OrdenCompraDetalle(OrdenCompraDetalleId id, BigDecimal precioUnitario, BigDecimal precioUnitarioFinal, 
			int cantidad, int cantidadFinal, Producto producto) {
		this.id = id;
		this.precioUnitario = precioUnitario;
		this.cantidad = cantidad;
		this.precioUnitarioFinal = precioUnitarioFinal;
		//this.cantidadFinal = cantidadFinal;
		this.producto = producto;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idOrdenCompra", column = @Column(name = "id_orden_compra", nullable = false)),
			@AttributeOverride(name = "idProducto", column = @Column(name = "id_producto", nullable = false)) })
	public OrdenCompraDetalleId getId() {
		return this.id;
	}

	public void setId(OrdenCompraDetalleId id) {
		this.id = id;
	}

	@Column(name = "precio_unitario", nullable = false, precision = 15)
	public BigDecimal getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(BigDecimal precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	@Column(name = "precio_unitario_final", nullable = false, precision = 15)
	public BigDecimal getPrecioUnitarioFinal() {
		return this.precioUnitarioFinal;
	}

	public void setPrecioUnitarioFinal(BigDecimal precioUnitarioFinal) {
		this.precioUnitarioFinal = precioUnitarioFinal;
	}
	
	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}
	
/*	@Column(name = "cantidad_final", nullable = false)
	public int getCantidadFinal() {
		return this.cantidadFinal;
	}

	public void setCantidadFinal(int cantidadFinal) {
		this.cantidadFinal = cantidadFinal;
	}*/
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_producto", nullable = false, insertable = false, updatable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

}
