package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 09-jul-2017 19:14:48 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrdenCompra generated by hbm2java
 */
@Entity
@Table(name = "orden_compra", catalog = "posAztlanbd")
public class OrdenCompra implements java.io.Serializable {

	private Integer idOrdenCompra;
	private int idProveedor;
	private BigDecimal descuento;
	private int folio;
	private EstatusOrdenCompra estatusOrdenCompra;
	private Empresa empresa;
	private BigDecimal total;

	public OrdenCompra() {
	}

	public OrdenCompra(int idProveedor, BigDecimal descuento, int folio, EstatusOrdenCompra estatusOrdenCompra, Empresa empresa, BigDecimal total) {
		this.idProveedor = idProveedor;
		this.descuento = descuento;
		this.folio = folio;
		this.estatusOrdenCompra = estatusOrdenCompra;
		this.empresa = empresa;
		this.total = total;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_orden_compra", unique = true, nullable = false)
	public Integer getIdOrdenCompra() {
		return this.idOrdenCompra;
	}

	public void setIdOrdenCompra(Integer idOrdenCompra) {
		this.idOrdenCompra = idOrdenCompra;
	}

	@Column(name = "id_proveedor", nullable = false)
	public int getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(int idProveedor) {
		this.idProveedor = idProveedor;
	}

	@Column(name = "descuento", nullable = false, precision = 15)
	public BigDecimal getDescuento() {
		return this.descuento;
	}

	public void setDescuento(BigDecimal descuento) {
		this.descuento = descuento;
	}

	@Column(name = "folio", nullable = false)
	public int getFolio() {
		return this.folio;
	}

	public void setFolio(int folio) {
		this.folio = folio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estatus_orden_compra", nullable = false)
	public EstatusOrdenCompra getEstatusOrdenCompra() {
		return this.estatusOrdenCompra;
	}

	public void setEstatusOrdenCompra(EstatusOrdenCompra estatusOrdenCompra) {
		this.estatusOrdenCompra = estatusOrdenCompra;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_Empresa", nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}
	@Column(name = "total", nullable = false)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}
}
