package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 09-jul-2017 19:14:48 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OrdenCompraDetalle generated by hbm2java
 */
@Entity
@Table(name = "orden_compra_detalle", catalog = "posAztlanbd")
public class OrdenCompraDetalle implements java.io.Serializable {

	private OrdenCompraDetalleId id;
	private BigDecimal precioUnitario;
	private int cantidad;

	public OrdenCompraDetalle() {
	}

	public OrdenCompraDetalle(OrdenCompraDetalleId id, BigDecimal precioUnitario, int cantidad) {
		this.id = id;
		this.precioUnitario = precioUnitario;
		this.cantidad = cantidad;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idOrdenCompra", column = @Column(name = "id_orden_compra", nullable = false)),
			@AttributeOverride(name = "idProducto", column = @Column(name = "id_producto", nullable = false)) })
	public OrdenCompraDetalleId getId() {
		return this.id;
	}

	public void setId(OrdenCompraDetalleId id) {
		this.id = id;
	}

	@Column(name = "precio_unitario", nullable = false, precision = 15)
	public BigDecimal getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(BigDecimal precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}
}
