package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 09-jul-2017 19:14:48 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdenCompraDetalleId generated by hbm2java
 */
@Embeddable
public class OrdenCompraDetalleId implements java.io.Serializable {

	private int idOrdenCompra;
	private int idProducto;

	public OrdenCompraDetalleId() {
	}

	public OrdenCompraDetalleId(int idOrdenCompra, int idProducto) {
		this.idOrdenCompra = idOrdenCompra;
		this.idProducto = idProducto;
	}

	@Column(name = "id_orden_compra", nullable = false)
	public int getIdOrdenCompra() {
		return this.idOrdenCompra;
	}

	public void setIdOrdenCompra(int idOrdenCompra) {
		this.idOrdenCompra = idOrdenCompra;
	}

	@Column(name = "id_producto", nullable = false)
	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdenCompraDetalleId))
			return false;
		OrdenCompraDetalleId castOther = (OrdenCompraDetalleId) other;

		return (this.getIdOrdenCompra() == castOther.getIdOrdenCompra())
				&& (this.getIdProducto() == castOther.getIdProducto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdOrdenCompra();
		result = 37 * result + this.getIdProducto();
		return result;
	}

}
