package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrecioXCanalId generated by hbm2java
 */
@Embeddable
public class PrecioXCanalId implements java.io.Serializable {

	private int idCanal;
	private int idProducto;

	public PrecioXCanalId() {
	}

	public PrecioXCanalId(int idCanal, int idProducto) {
		this.idCanal = idCanal;
		this.idProducto = idProducto;
	}

	@Column(name = "id_canal", nullable = false)
	public int getIdCanal() {
		return this.idCanal;
	}

	public void setIdCanal(int idCanal) {
		this.idCanal = idCanal;
	}

	@Column(name = "id_producto", nullable = false)
	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrecioXCanalId))
			return false;
		PrecioXCanalId castOther = (PrecioXCanalId) other;

		return (this.getIdCanal() == castOther.getIdCanal())
				&& (this.getIdProducto() == castOther.getIdProducto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProducto();
		result = 37 * result + this.getIdCanal();
		return result;
	}

}
