package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductosXPuntoVenta generated by hbm2java
 */
@Entity
@Table(name = "precio_x_canal", catalog = "posaztlanbd")
public class PrecioXCanal implements java.io.Serializable {

	private PrecioXCanalId id;
	private Producto producto;
	private Canal canal;
	private BigDecimal precio;
	
	public PrecioXCanal() {
	}

	public PrecioXCanal(PrecioXCanalId id, Producto producto, Canal canal, BigDecimal precio) {
		this.id = id;
		this.producto = producto;
		this.canal = canal;
		this.precio = precio;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idCanal", column = @Column(name = "id_canal", nullable = false)),
			@AttributeOverride(name = "idProducto", column = @Column(name = "id_producto", nullable = false)) })
	public PrecioXCanalId getId() {
		return this.id;
	}

	public void setId(PrecioXCanalId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_producto", nullable = false, insertable = false, updatable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_canal", nullable = false, insertable = false, updatable = false)
	public Canal getCanal() {
		return this.canal;
	}

	public void setCanal(Canal canal) {
		this.canal = canal;
	}
	
	@Column(name = "precio", nullable = false, precision = 15)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}
}
