package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovimientoInventario generated by hbm2java
 */
@Entity
@Table(name = "productos_corte", catalog = "posaztlanbd")
public class ProductosCorte implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2125072180805299682L;
	private Integer idProductoCorte;
	private Producto producto;
	private Usuario usuario;
	private long existenciaFisica;
	private long existenciaSistema;
	private Integer estatusConteo;
	private Date fecha;
	private Almacen almacen;
	private Date ultimaModificacion;
	private Usuario usuarioModificacion;	
	
	public ProductosCorte(Integer idProductoCorte, Producto producto, Usuario usuario, long existenciaFisica,
			long existenciaSistema, Integer estatusConteo, Date fecha, Almacen almacen, Date ultimaModificacion,
			Usuario usuarioModificacion) {
		super();
		this.idProductoCorte = idProductoCorte;
		this.producto = producto;
		this.usuario = usuario;
		this.existenciaFisica = existenciaFisica;
		this.existenciaSistema = existenciaSistema;
		this.estatusConteo = estatusConteo;
		this.fecha = fecha;
		this.almacen = almacen;
		this.ultimaModificacion = ultimaModificacion;
		this.usuarioModificacion = usuarioModificacion;
	}

	public ProductosCorte() {
		super();
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_producto_corte", unique = true, nullable = false)
	public Integer getIdProductoCorte() {
		return idProductoCorte;
	}

	public void setIdProductoCorte(Integer idProductoCorte) {
		this.idProductoCorte = idProductoCorte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_producto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	
	@Column(name = "existencia_fisica", nullable = false)
	public long getExistenciaFisica() {
		return existenciaFisica;
	}
	
	public void setExistenciaFisica(long existenciaFisica) {
		this.existenciaFisica = existenciaFisica;
	}

	@Column(name = "existencia_sistema", nullable = false)
	public long getExistenciaSistema() {
		return existenciaSistema;
	}

	public void setExistenciaSistema(long existenciaSistema) {
		this.existenciaSistema = existenciaSistema;
	}
	
	@Column(name = "estatus_conteo", nullable = false)
	public Integer getEstatusConteo() {
		return estatusConteo;
	}
	
	public void setEstatusConteo(Integer estatusConteo) {
		this.estatusConteo = estatusConteo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_almacen", nullable = false)
	public Almacen getAlmacen() {
		return almacen;
	}

	public void setAlmacen(Almacen almacen) {
		this.almacen = almacen;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ultima_modificacion", nullable = false, length = 10)
	public Date getUltimaModificacion() {
		return this.ultimaModificacion;
	}

	public void setUltimaModificacion(Date ultimaModificacion) {
		this.ultimaModificacion = ultimaModificacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario_modificacion", nullable = false)
	public Usuario getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuario;
	}
}
