package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductosXPuntoVentaId generated by hbm2java
 */
@Embeddable
public class ProductosXAlmacenId implements java.io.Serializable {

	private int idAlmacen;
	private int idProducto;

	public ProductosXAlmacenId() {
	}

	public ProductosXAlmacenId(int idAlmacen, int idProducto) {
		this.idAlmacen = idAlmacen;
		this.idProducto = idProducto;
	}

	@Column(name = "id_almacen", nullable = false)
	public int getIdAlmacen() {
		return this.idAlmacen;
	}

	public void setIdAlmacen(int idAlmacen) {
		this.idAlmacen = idAlmacen;
	}

	@Column(name = "id_producto", nullable = false)
	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductosXAlmacenId))
			return false;
		ProductosXAlmacenId castOther = (ProductosXAlmacenId) other;

		return (this.getIdAlmacen() == castOther.getIdAlmacen())
				&& (this.getIdProducto() == castOther.getIdProducto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAlmacen();
		result = 37 * result + this.getIdProducto();
		return result;
	}

}
