package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 28-may-2017 1:06:14 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PropiedadConfig generated by hbm2java
 */
@Entity
@Table(name = "propiedad_config", catalog = "posaztlanbd")
public class PropiedadConfig implements java.io.Serializable {

	private int idPropiedadConfig;
	private String nombre;
	private String valor;
	private String valorExtra;

	public PropiedadConfig() {
	}

	public PropiedadConfig(int idPropiedadConfig, String nombre, String valor) {
		this.idPropiedadConfig = idPropiedadConfig;
		this.nombre = nombre;
		this.valor = valor;
	}

	public PropiedadConfig(int idPropiedadConfig, String nombre, String valor, String valorExtra) {
		this.idPropiedadConfig = idPropiedadConfig;
		this.nombre = nombre;
		this.valor = valor;
		this.valorExtra = valorExtra;
	}

	@Id

	@Column(name = "id_propiedad_config", unique = true, nullable = false)
	public int getIdPropiedadConfig() {
		return this.idPropiedadConfig;
	}

	public void setIdPropiedadConfig(int idPropiedadConfig) {
		this.idPropiedadConfig = idPropiedadConfig;
	}

	@Column(name = "nombre", nullable = false, length = 80)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "valor", nullable = false, length = 200)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "valor_extra", length = 200)
	public String getValorExtra() {
		return this.valorExtra;
	}

	public void setValorExtra(String valorExtra) {
		this.valorExtra = valorExtra;
	}

}
