package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 28-may-2017 1:06:14 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PropiedadConfig generated by hbm2java
 */
@Entity
@Table(name = "propiedad_config_empresa", catalog = "posaztlanbd")
public class PropiedadConfigEmpresa implements java.io.Serializable {

	private Empresa empresa;
	private boolean validarExistenciaInv;
	private String secuenciaCreacionSku;

	public PropiedadConfigEmpresa() {
	}


	@Id
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_Empresa", unique = true, nullable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "secuencia_creacion_sku", nullable = false, length = 45)
	public String getSecuenciaCreacionSku() {
		return this.secuenciaCreacionSku;
	}

	public void setSecuenciaCreacionSku(String secuenciaCreacionSku) {
		this.secuenciaCreacionSku = secuenciaCreacionSku;
	}

	@Column(name = "validar_existencia_inv", nullable = false)
	public boolean isValidarExistenciaInv() {
		return this.validarExistenciaInv;
	}

	public void setValidarExistenciaInv(boolean validarExistenciaInv) {
		this.validarExistenciaInv = validarExistenciaInv;
	}

}
