package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pelicula generated by hbm2java
 */
@Entity
@Table(name = "reportes_distribuidora", catalog = "posaztlanbd")
public class ReportesDistribuidora implements java.io.Serializable {

	private Integer idReporteDistribuidora;
	private String nombre;
	private String rutaReporteJasper;
	private String rutaReporteXls;
	private String rutaPlantillaVm;
	private String rutaPlantillaVmError;	
	
	public ReportesDistribuidora() {
	}
	
	public ReportesDistribuidora(Integer idReporteDistribuidora, String nombre, String rutaReporteJasper,
			String rutaReporteXls, String rutaPlantillaVm, String rutaPlantillaVmError) {
		super();
		this.idReporteDistribuidora = idReporteDistribuidora;
		this.nombre = nombre;
		this.rutaReporteJasper = rutaReporteJasper;
		this.rutaReporteXls = rutaReporteXls;
		this.rutaPlantillaVm = rutaPlantillaVm;
		this.rutaPlantillaVmError = rutaPlantillaVmError;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_reporte_distribuidora", unique = true, nullable = false)
	public Integer getIdReporteDistribuidora() {
		return this.idReporteDistribuidora;
	}

	public void setIdReporteDistribuidora(Integer idReporteDistribuidora) {
		this.idReporteDistribuidora = idReporteDistribuidora;
	}
	
	@Column(name = "nombre", nullable = false, length = 2000)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@Column(name = "ruta_reporte_jasper", nullable = false, length = 200)
	public String getRutaReporteJasper() {
		return rutaReporteJasper;
	}

	public void setRutaReporteJasper(String rutaReporteJasper) {
		this.rutaReporteJasper = rutaReporteJasper;
	}

	@Column(name = "ruta_reporte_xls", nullable = false, length = 200)
	public String getRutaReporteXls() {
		return rutaReporteXls;
	}

	public void setRutaReporteXls(String rutaReporteXls) {
		this.rutaReporteXls = rutaReporteXls;
	}

	@Column(name = "ruta_plantilla_vm", nullable = false, length = 200)
	public String getRutaPlantillaVm() {
		return rutaPlantillaVm;
	}

	public void setRutaPlantillaVm(String rutaPlantillaVm) {
		this.rutaPlantillaVm = rutaPlantillaVm;
	}
	
	@Column(name = "ruta_plantilla_vm_error", nullable = false, length = 200)
	public String getRutaPlantillaVmError() {
		return rutaPlantillaVmError;
	}

	public void setRutaPlantillaVmError(String rutaPlantillaVmError) {
		this.rutaPlantillaVmError = rutaPlantillaVmError;
	}

}
