package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 28-may-2017 1:06:14 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoAutorizacion generated by hbm2java
 */
@Entity
@Table(name = "tipo_autorizacion", catalog = "posaztlanbd")
public class TipoAutorizacion implements java.io.Serializable {

	private Integer idTipoAutorizacion;
	private String nombre;
	private boolean activo;
	private Set<Autorizacion> autorizacions = new HashSet<Autorizacion>(0);
	private Set<TipoAutorizacionXPerfil> tipoAutorizacionXPerfils = new HashSet<TipoAutorizacionXPerfil>(0);

	public TipoAutorizacion() {
	}

	public TipoAutorizacion(Integer idTipoAutorizacion) {
		this.idTipoAutorizacion = idTipoAutorizacion;
	}
	
	public TipoAutorizacion(String nombre, boolean activo) {
		this.nombre = nombre;
		this.activo = activo;
	}

	public TipoAutorizacion(String nombre, boolean activo, Set<Autorizacion> autorizacions,
			Set<TipoAutorizacionXPerfil> tipoAutorizacionXPerfils) {
		this.nombre = nombre;
		this.activo = activo;
		this.autorizacions = autorizacions;
		this.tipoAutorizacionXPerfils = tipoAutorizacionXPerfils;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tipo_autorizacion", unique = true, nullable = false)
	public Integer getIdTipoAutorizacion() {
		return this.idTipoAutorizacion;
	}

	public void setIdTipoAutorizacion(Integer idTipoAutorizacion) {
		this.idTipoAutorizacion = idTipoAutorizacion;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAutorizacion")
	public Set<Autorizacion> getAutorizacions() {
		return this.autorizacions;
	}

	public void setAutorizacions(Set<Autorizacion> autorizacions) {
		this.autorizacions = autorizacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAutorizacion")
	public Set<TipoAutorizacionXPerfil> getTipoAutorizacionXPerfils() {
		return this.tipoAutorizacionXPerfils;
	}

	public void setTipoAutorizacionXPerfils(Set<TipoAutorizacionXPerfil> tipoAutorizacionXPerfils) {
		this.tipoAutorizacionXPerfils = tipoAutorizacionXPerfils;
	}

}
