package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 05-jun-2017 0:25:12 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPuntoVenta generated by hbm2java
 */
@Entity
@Table(name = "tipo_almacen", catalog = "posaztlanbd")
public class TipoAlmacen implements java.io.Serializable {

	private Integer idTipoAlmacen;
	private String nombre;
	private String descripcion;
	private String clave;
	private Set<Almacen> almacenes = new HashSet<Almacen>(0);

	public TipoAlmacen() {
	}

	public TipoAlmacen(String nombre, String clave) {
		this.nombre = nombre;
		this.clave = clave;
	}

	public TipoAlmacen(String nombre, String descripcion, String clave, Set<Almacen> almacenes,
			Set<TipoDevolucion> tipoDevolucions) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.clave = clave;
		this.almacenes = almacenes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tipo_almacen", unique = true, nullable = false)
	public Integer getIdTipoAlmacen() {
		return this.idTipoAlmacen;
	}

	public void setIdTipoAlmacen(Integer idTipoAlmacen) {
		this.idTipoAlmacen = idTipoAlmacen;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "clave", nullable = false, length = 25)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAlmacen")
	public Set<Almacen> getAlmacenes() {
		return this.almacenes;
	}

	public void setAlmacenes(Set<Almacen> almacenes) {
		this.almacenes = almacenes;
	}

}
