package mx.com.aztlan.pos.infraservices.persistencia.posaztlanbd.dto;
// Generated 28-may-2017 1:06:14 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TipoAutorizacionXPerfil generated by hbm2java
 */
@Entity
@Table(name = "tipo_autorizacion_x_perfil", catalog = "posaztlanbd")
public class TipoAutorizacionXPerfil implements java.io.Serializable {

	private TipoAutorizacionXPerfilId id;
	private Perfil perfil;
	private TipoAutorizacion tipoAutorizacion;

	public TipoAutorizacionXPerfil() {
	}

	public TipoAutorizacionXPerfil(TipoAutorizacionXPerfilId id, Perfil perfil, TipoAutorizacion tipoAutorizacion) {
		this.id = id;
		this.perfil = perfil;
		this.tipoAutorizacion = tipoAutorizacion;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idPerfil", column = @Column(name = "id_perfil", nullable = false)),
			@AttributeOverride(name = "idTipoAutorizacion", column = @Column(name = "id_tipo_autorizacion", nullable = false)) })
	public TipoAutorizacionXPerfilId getId() {
		return this.id;
	}

	public void setId(TipoAutorizacionXPerfilId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_perfil", nullable = false, insertable = false, updatable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_autorizacion", nullable = false, insertable = false, updatable = false)
	public TipoAutorizacion getTipoAutorizacion() {
		return this.tipoAutorizacion;
	}

	public void setTipoAutorizacion(TipoAutorizacion tipoAutorizacion) {
		this.tipoAutorizacion = tipoAutorizacion;
	}

}
