package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovimientoInventario generated by hbm2java
 */
@Entity
@Table(name = "articulo_corte_ajuste", catalog = "muvitul")
public class ArticulosCorteAjuste implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2125072180805299682L;
	private Integer idArticuloCorteAjuste;
	private ArticulosCorte articuloCorte;
	private MovimientoInventario movimientoInventario;
	private Usuario usuario;
	private Date fecha;
	
	
	public ArticulosCorteAjuste() {
	}

	public ArticulosCorteAjuste(Integer idArticuloCorteAjuste, ArticulosCorte articuloCorte, Usuario usuario, Date fecha,
			MovimientoInventario movimientoInventario) {
		super();
		this.idArticuloCorteAjuste = idArticuloCorteAjuste;
		this.articuloCorte = articuloCorte;
		this.usuario = usuario;
		this.fecha = fecha;
		this.movimientoInventario = movimientoInventario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idArticuloCorteAjuste", unique = true, nullable = false)
	public Integer getIdArticuloCorteAjuste() {
		return idArticuloCorteAjuste;
	}

	public void setIdArticuloCorteAjuste(Integer idArticuloCorteAjuste) {
		this.idArticuloCorteAjuste = idArticuloCorteAjuste;
	}	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_articulo_corte", nullable = false)
	public ArticulosCorte getArticuloCorte() {
		return articuloCorte;
	}

	public void setArticuloCorte(ArticulosCorte articuloCorte) {
		this.articuloCorte = articuloCorte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_movimiento", nullable = false)
	public MovimientoInventario getMovimientoInventario() {
		return movimientoInventario;
	}

	public void setMovimientoInventario(MovimientoInventario movimientoInventario) {
		this.movimientoInventario = movimientoInventario;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}
	
}
