package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PuntoVenta generated by hbm2java
 */
@Entity
@Table(name = "cargo_ajuste", catalog = "muvitul")
public class CargoAjuste implements java.io.Serializable {

	private Integer idCargoAjuste;
	private String nombre;
	private boolean activo;
	private Set<CorteCaja> corteCajas = new HashSet<CorteCaja>(0);
	
	public CargoAjuste() {
	}
	
	public CargoAjuste(Integer idCargoAjuste) {
		this.idCargoAjuste = idCargoAjuste;
	}
	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_cargo_ajuste", unique = true, nullable = false)
	public Integer getIdCargoAjuste() {
		return this.idCargoAjuste;
	}

	public void setIdCargoAjuste(Integer idCargoAjuste) {
		this.idCargoAjuste = idCargoAjuste;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}	
	
	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargoAjuste")
	public Set<CorteCaja> getCorteCajas() {
		return this.corteCajas;
	}

	public void setCorteCajas(Set<CorteCaja> corteCajas) {
		this.corteCajas = corteCajas;
	}
}
