package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 05-jun-2017 0:25:12 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstatusPago generated by hbm2java
 */
@Entity
@Table(name = "estatus_pago", catalog = "muvitul")
public class EstatusPago implements java.io.Serializable {

	private Integer idEstatus;
	private String nombre;
	private String clave;
	private Set<Pago> pagos = new HashSet<Pago>(0);

	public EstatusPago() {
	}

	public EstatusPago(String nombre, String clave) {
		this.nombre = nombre;
		this.clave = clave;
	}

	public EstatusPago(String nombre, String clave, Set<Pago> pagos) {
		this.nombre = nombre;
		this.clave = clave;
		this.pagos = pagos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_estatus", unique = true, nullable = false)
	public Integer getIdEstatus() {
		return this.idEstatus;
	}

	public void setIdEstatus(Integer idEstatus) {
		this.idEstatus = idEstatus;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "clave", nullable = false, length = 25)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusPago")
	public Set<Pago> getPagos() {
		return this.pagos;
	}

	public void setPagos(Set<Pago> pagos) {
		this.pagos = pagos;
	}

}
