package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 07-jun-2017 0:11:27 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoDevolucion generated by hbm2java
 */
@Entity
@Table(name = "tipo_devolucion", catalog = "muvitul")
public class TipoDevolucion implements java.io.Serializable {

	private Integer idTipoDevolucion;
	private TipoPuntoVenta tipoPuntoVenta;
	private String nombre;
	private boolean activo;
	private String clave;
	private Set<Devolucion> devolucions = new HashSet<Devolucion>(0);

	public TipoDevolucion() {
	}

	public TipoDevolucion(TipoPuntoVenta tipoPuntoVenta, String nombre, boolean activo, String clave) {
		this.tipoPuntoVenta = tipoPuntoVenta;
		this.nombre = nombre;
		this.activo = activo;
		this.clave = clave;
	}

	public TipoDevolucion(TipoPuntoVenta tipoPuntoVenta, String nombre, boolean activo, String clave,
			Set<Devolucion> devolucions) {
		this.tipoPuntoVenta = tipoPuntoVenta;
		this.nombre = nombre;
		this.activo = activo;
		this.clave = clave;
		this.devolucions = devolucions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tipo_devolucion", unique = true, nullable = false)
	public Integer getIdTipoDevolucion() {
		return this.idTipoDevolucion;
	}

	public void setIdTipoDevolucion(Integer idTipoDevolucion) {
		this.idTipoDevolucion = idTipoDevolucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_punto_venta", nullable = false)
	public TipoPuntoVenta getTipoPuntoVenta() {
		return this.tipoPuntoVenta;
	}

	public void setTipoPuntoVenta(TipoPuntoVenta tipoPuntoVenta) {
		this.tipoPuntoVenta = tipoPuntoVenta;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "clave", nullable = false, length = 25)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDevolucion")
	public Set<Devolucion> getDevolucions() {
		return this.devolucions;
	}

	public void setDevolucions(Set<Devolucion> devolucions) {
		this.devolucions = devolucions;
	}

}
