package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 09-jul-2017 19:14:48 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoProducto generated by hbm2java
 */
@Entity
@Table(name = "estado_producto", catalog = "muvitul")
public class EstadoProducto implements java.io.Serializable {

	private Integer idEstadoProducto;
	private String nombre;
	private boolean activo;
	private String clave;
	private Set<DevolucionXProducto> devolucionXProductos = new HashSet<DevolucionXProducto>(0);

	public EstadoProducto() {
	}

	public EstadoProducto(String nombre, boolean activo, String clave) {
		this.nombre = nombre;
		this.activo = activo;
		this.clave = clave;
	}

	public EstadoProducto(String nombre, boolean activo, String clave, Set<DevolucionXProducto> devolucionXProductos) {
		this.nombre = nombre;
		this.activo = activo;
		this.clave = clave;
		this.devolucionXProductos = devolucionXProductos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_estado_producto", unique = true, nullable = false)
	public Integer getIdEstadoProducto() {
		return this.idEstadoProducto;
	}

	public void setIdEstadoProducto(Integer idEstadoProducto) {
		this.idEstadoProducto = idEstadoProducto;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "clave", nullable = false, length = 25)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoProducto")
	public Set<DevolucionXProducto> getDevolucionXProductos() {
		return this.devolucionXProductos;
	}

	public void setDevolucionXProductos(Set<DevolucionXProducto> devolucionXProductos) {
		this.devolucionXProductos = devolucionXProductos;
	}

}
