package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-may-2017 0:27:41 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ImpuestosXTicketPaquete generated by hbm2java
 */
@Entity
@Table(name = "impuestos_x_ticket_paquete", catalog = "muvitul")
public class ImpuestosXTicketPaquete implements java.io.Serializable {

	private Integer idImpuestoTicketPaquete;
	private TicketVenta ticketVenta;
	private BigDecimal importe;
	private BigDecimal porcentaje;

	public ImpuestosXTicketPaquete() {
	}

	public ImpuestosXTicketPaquete(TicketVenta ticketVenta, BigDecimal importe, BigDecimal porcentaje) {
		this.ticketVenta = ticketVenta;
		this.importe = importe;
		this.porcentaje = porcentaje;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_impuesto_ticket_paquete", unique = true, nullable = false)
	public Integer getIdImpuestoTicketPaquete() {
		return this.idImpuestoTicketPaquete;
	}

	public void setIdImpuestoTicketPaquete(Integer idImpuestoTicketPaquete) {
		this.idImpuestoTicketPaquete = idImpuestoTicketPaquete;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ticket", nullable = false)
	public TicketVenta getTicketVenta() {
		return this.ticketVenta;
	}

	public void setTicketVenta(TicketVenta ticketVenta) {
		this.ticketVenta = ticketVenta;
	}

	@Column(name = "importe", nullable = false, precision = 15)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Column(name = "porcentaje", nullable = false, precision = 15)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

}
