package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 14-abr-2017 14:25:39 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pelicula generated by hbm2java
 */
@Entity
@Table(name = "reportes_cine_x_distribuidora", catalog = "muvitul")
public class ReportesCineXDistribuidora implements java.io.Serializable {

	private Integer idReporte;
	private Cine cine;
	private Pelicula pelicula;
	private Distribuidora distribuidora;
	private Date fechaInicio;
	private Date fechaFin;
	private String rutaReporteJasper;
	private String rutaReporteXls;
	private String rutaPlantillaVm;
	private String rutaPlantillaVmError;
	private String destinatarios;
	private String asunto;
	private Integer diasPeriodo;
	private Integer diasEnvio;	
	private Date fechaEnvio;
	private String emailError;
	private boolean activo;
	
	public ReportesCineXDistribuidora() {
	}

	public ReportesCineXDistribuidora(Integer idReporte, Cine cine, Pelicula pelicula, Distribuidora distribuidora,
			Date fechaInicio, Date fechaFin, String rutaReporteJasper, String rutaReporteXls, String rutaPlantillaVm,
			String rutaPlantillaVmError, String destinatarios, String asunto, Integer diasPeriodo, Integer diasEnvio,
			Date fechaEnvio, String emailError, boolean activo) {
		super();
		this.idReporte = idReporte;
		this.cine = cine;
		this.pelicula = pelicula;
		this.distribuidora = distribuidora;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.rutaReporteJasper = rutaReporteJasper;
		this.rutaReporteXls = rutaReporteXls;
		this.rutaPlantillaVm = rutaPlantillaVm;
		this.rutaPlantillaVmError = rutaPlantillaVmError;
		this.destinatarios = destinatarios;
		this.asunto = asunto;
		this.diasPeriodo = diasPeriodo;
		this.diasEnvio = diasEnvio;
		this.fechaEnvio = fechaEnvio;
		this.emailError = emailError;
		this.activo = activo;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_reporte", unique = true, nullable = false)
	public Integer getIdReporte() {
		return this.idReporte;
	}

	public void setIdReporte(Integer idReporte) {
		this.idReporte = idReporte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cine", nullable = false)
	public Cine getCine() {
		return this.cine;
	}

	public void setCine(Cine cine) {
		this.cine = cine;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pelicula", nullable = false)
	public Pelicula getPelicula() {
		return this.pelicula;
	}

	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_distribuidora", nullable = false)
	public Distribuidora getDistribuidora() {
		return this.distribuidora;
	}

	public void setDistribuidora(Distribuidora distribuidora) {
		this.distribuidora = distribuidora;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_inicio", nullable = false, length = 19)
	public Date getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_fin", nullable = false, length = 19)
	public Date getFechaFin() {
		return fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}
	
	@Column(name = "ruta_reporte_jasper", nullable = false, length = 200)
	public String getRutaReporteJasper() {
		return rutaReporteJasper;
	}

	public void setRutaReporteJasper(String rutaReporteJasper) {
		this.rutaReporteJasper = rutaReporteJasper;
	}

	@Column(name = "ruta_reporte_xls", nullable = false, length = 200)
	public String getRutaReporteXls() {
		return rutaReporteXls;
	}

	public void setRutaReporteXls(String rutaReporteXls) {
		this.rutaReporteXls = rutaReporteXls;
	}

	@Column(name = "ruta_plantilla_vm", nullable = false, length = 200)
	public String getRutaPlantillaVm() {
		return rutaPlantillaVm;
	}

	public void setRutaPlantillaVm(String rutaPlantillaVm) {
		this.rutaPlantillaVm = rutaPlantillaVm;
	}
	
	@Column(name = "ruta_plantilla_vm_error", nullable = false, length = 200)
	public String getRutaPlantillaVmError() {
		return rutaPlantillaVmError;
	}

	public void setRutaPlantillaVmError(String rutaPlantillaVmError) {
		this.rutaPlantillaVmError = rutaPlantillaVmError;
	}

	@Column(name = "destinatarios", nullable = false, length = 2000)
	public String getDestinatarios() {
		return this.destinatarios;
	}

	public void setDestinatarios(String destinatarios) {
		this.destinatarios = destinatarios;
	}

	@Column(name = "asunto", nullable = true, length = 200)
	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	@Column(name = "dias_periodo", nullable = false)
	public int getDiasPeriodo() {
		return this.diasPeriodo;
	}

	public void setDiasPeriodo(Integer diasPeriodo) {
		this.diasPeriodo = diasPeriodo;
	}
	
	@Column(name = "dias_envio", nullable = false)
	public int getDiasEnvio() {
		return this.diasEnvio;
	}

	public void setDiasEnvio(Integer diasEnvio) {
		this.diasEnvio = diasEnvio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_envio", nullable = false, length = 19)
	public Date getFechaEnvio() {
		return fechaEnvio;
	}

	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}
	
	@Column(name = "email_error", nullable = false, length = 2000)
	public String getEmailError() {
		return emailError;
	}

	public void setEmailError(String emailError) {
		this.emailError = emailError;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
