package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 28-may-2017 1:06:14 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TipoAutorizacionXPerfilId generated by hbm2java
 */
@Embeddable
public class TipoAutorizacionXPerfilId implements java.io.Serializable {

	private int idPerfil;
	private int idTipoAutorizacion;

	public TipoAutorizacionXPerfilId() {
	}

	public TipoAutorizacionXPerfilId(int idPerfil, int idTipoAutorizacion) {
		this.idPerfil = idPerfil;
		this.idTipoAutorizacion = idTipoAutorizacion;
	}

	@Column(name = "id_perfil", nullable = false)
	public int getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	@Column(name = "id_tipo_autorizacion", nullable = false)
	public int getIdTipoAutorizacion() {
		return this.idTipoAutorizacion;
	}

	public void setIdTipoAutorizacion(int idTipoAutorizacion) {
		this.idTipoAutorizacion = idTipoAutorizacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TipoAutorizacionXPerfilId))
			return false;
		TipoAutorizacionXPerfilId castOther = (TipoAutorizacionXPerfilId) other;

		return (this.getIdPerfil() == castOther.getIdPerfil())
				&& (this.getIdTipoAutorizacion() == castOther.getIdTipoAutorizacion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPerfil();
		result = 37 * result + this.getIdTipoAutorizacion();
		return result;
	}

}
