package mx.com.tecnetia.muvitul.infraservices.persistencia.muvitul.dto;
// Generated 05-jun-2017 0:25:12 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPuntoVenta generated by hbm2java
 */
@Entity
@Table(name = "tipo_punto_venta", catalog = "muvitul")
public class TipoPuntoVenta implements java.io.Serializable {

	private Integer idTipoPuntoVenta;
	private String nombre;
	private String descripcion;
	private String clave;
	private Set<PuntoVenta> puntoVentas = new HashSet<PuntoVenta>(0);
	private Set<TipoDevolucion> tipoDevolucions = new HashSet<TipoDevolucion>(0);

	public TipoPuntoVenta() {
	}

	public TipoPuntoVenta(String nombre, String clave) {
		this.nombre = nombre;
		this.clave = clave;
	}

	public TipoPuntoVenta(String nombre, String descripcion, String clave, Set<PuntoVenta> puntoVentas,
			Set<TipoDevolucion> tipoDevolucions) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.clave = clave;
		this.puntoVentas = puntoVentas;
		this.tipoDevolucions = tipoDevolucions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tipo_punto_venta", unique = true, nullable = false)
	public Integer getIdTipoPuntoVenta() {
		return this.idTipoPuntoVenta;
	}

	public void setIdTipoPuntoVenta(Integer idTipoPuntoVenta) {
		this.idTipoPuntoVenta = idTipoPuntoVenta;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "clave", nullable = false, length = 25)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPuntoVenta")
	public Set<PuntoVenta> getPuntoVentas() {
		return this.puntoVentas;
	}

	public void setPuntoVentas(Set<PuntoVenta> puntoVentas) {
		this.puntoVentas = puntoVentas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPuntoVenta")
	public Set<TipoDevolucion> getTipoDevolucions() {
		return this.tipoDevolucions;
	}

	public void setTipoDevolucions(Set<TipoDevolucion> tipoDevolucions) {
		this.tipoDevolucions = tipoDevolucions;
	}

}
